name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: archlinux
    strategy:
      matrix:
        compiler: [g++, clang++]

    steps:
      - uses: actions/checkout@v2

      - name: Install libraries and tools
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel clang lld llvm cmake gtest

      - name: CMake
        env:
          CXX: ${{ matrix.compiler }}
        run: mkdir build && cd build && cmake -DCLANG_TIDY=TRUE ..

      - name: Build
        run: cmake --build build -j$(nproc) --target all

      - name: Execute tests
        run: cd build && ctest -j$(nproc) --output-on-failure

      - name: Install
        run: cmake --build build --target install
